package my.monopoly;

import java.awt.MouseInfo;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.Color;

/**
 *
 * @author 335633277
 */
public class MonopolyUI extends java.awt.Frame {

    Graphics g;

    int curPos[] = {0, 0, 0, 0};
    int xC[] = {560, 560, 560, 560, 560, 560, 430, 330, 230, 150, 21, 21, 21, 21, 21, 21, 170, 250, 330, 420};
    int yC[] = {560, 440, 340, 270, 160, 55, 55, 55, 55, 55, 55, 180, 260, 340, 440, 560, 560, 560, 560, 560};
    int cost[] = {200, 150, 0, 150, 200, 0, 250, 0, 250, 300, 0, 350, 0, 350, 400, 0, 450, 0, 450, 500};
    int rent[] = {20, 15, 0, 15, 20, 0, 25, 0, 25, 30, 0, 35, 0, 35, 40, 0, 45, 0, 45, 50};
    int owner[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int cash[] = {1000, 1000, 1000, 1000};
    String names[] = {"GO", "Argentina", "Community Chest", "Brazil", "Peru", "Just Visiting", "United Kingdom",
        "Chance", "Belgium", "France", "Free Parking", "Japan", "Community Chest", "Israel", "China", "Go to Jail",
        "Mexico", "Chance", "United States", "Canada"};
    int playerTurn = 1;

    public MonopolyUI() {
        initComponents();
        g = jPanel1.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/monopoly/Monopoly.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jButton2.setText("Play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/monopoly/6.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton4.setText("Quit");
        jButton4.setActionCommand("JButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Buy Property");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton2)
                        .addComponent(jButton4))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int tableX = 900;
        int tableY = 100;
        g.drawString("Property      Cost          Rent           Owner", tableX, tableY - 100);
        g.setColor(Color.white);
        g.fillRect(tableX - 50, tableY - 50, 400, 300);
        g.setColor(Color.black);

        
        for (int k = 0; k < 4; k++) {
            g.drawString(names[curPos[k]], tableX, tableY);
            g.drawString(String.valueOf(cost[curPos[k]]), tableX + 100, tableY);
            g.drawString(String.valueOf(rent[curPos[k]]), tableX + 150, tableY);
            g.drawString(String.valueOf(owner[curPos[k]]), tableX + 200, tableY);
            tableY = tableY + 20;
        }
        tableX = 900;
        tableY = 300;
        g.drawString("Player 1      Player 2      Player 3       Player4", tableX, tableY);
        tableY = tableY + 20;
        
        for (int w = 0; w < 4; w++) {
            //g.drawString(String.valueOf(cash[curPos[0]]), tableX, tableY);
            tableX = tableX + 64;
        }
        
        switch (playerTurn) {
            case 1:
                g.setColor(Color.white);
                g.fillOval(xC[curPos[0]], yC[curPos[0]], 10, 10);
                int numDie = (int) (Math.random() * 6) + 1;
                if (curPos[0] + numDie < 19) {
                    curPos[0] += numDie;
                    System.out.println(curPos[0]);
                } else {
                    curPos[0] = curPos[0] + numDie - 19;
                }
                g.setColor(Color.blue);
                g.fillOval(xC[curPos[0]], yC[curPos[0]], 10, 10);
                playerTurn = 2;
                showDie(numDie);
                break;
            case 2:
                g.setColor(Color.white);
                g.fillOval(xC[curPos[1]] + 10, yC[curPos[1]], 10, 10);
                numDie = (int) (Math.random() * 6) + 1;
                if (curPos[1] + numDie < 19) {
                    curPos[1] += numDie;
                    System.out.println(curPos[1]);
                } else {
                    curPos[1] = curPos[1] + numDie - 19;
                }
                g.setColor(Color.red);
                g.fillOval(xC[curPos[1]] + 10, yC[curPos[1]], 10, 10);
                playerTurn = 1;
                showDie(numDie);
                break;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked



    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyUI().setVisible(true);
            }
        });
    }

    public void showDie(int dieValue) {
        switch (dieValue) {
            case 1:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("1.png")));
                break;
            case 2:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("2.png")));
                break;
            case 3:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("3.png")));
                break;
            case 4:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("4.png")));
                break;
            case 5:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("5.png")));
                break;
            case 6:
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("6.png")));
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
